version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: php_docker
      MYSQL_USER: php_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: '0'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  www:
    image: php:apache
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    command: >
      bash -c "
        docker-php-ext-install mysqli &&
        chown -R www-data:www-data /var/www/html &&
        chmod -R 755 /var/www/html &&
        a2enmod rewrite &&
        echo '<VirtualHost *:80>
                DocumentRoot /var/www/html
                <Directory /var/www/html>
                    Options Indexes FollowSymLinks
                    AllowOverride All
                    Require all granted
                    DirectoryIndex index.php
                </Directory>
              </VirtualHost>' > /etc/apache2/sites-available/000-default.conf &&
        apache2-foreground
      "

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: '3306'
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
