version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-php_docker}
      - MYSQL_USER=${MYSQL_USER:-php_docker}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  www:
    image: php:apache
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
