version: '3'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.websecure.address=:8443"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - company_network

  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:\company:/var/www/html
    networks:
      - company_network
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`https://swk8g4g.curricula.com.ng`)"
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.services.php.loadbalancer.server.port=80"

  mysql:
    image: mysql:8.1.0
    container_name: mysql_8.1.0_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
      MYSQL_USER: root
    volumes:
      - C:\company\mysql:/var/lib/mysql
    networks:
      - company_network

  redis:
    image: redis:7.2.1
    container_name: redis_7.2.1_container
    restart: always
    networks:
      - company_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - company_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`https://z4c0g44.curricula.com.ng`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  company_network:
