version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_NAME=myapp
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
