version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-php_docker}
      - MYSQL_USER=${MYSQL_USER:-php_docker}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  www:
    image: php:apache
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 8443:443  # Changed from 443:443 to 8443:443
    depends_on:
      - db
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
