version: '3.8'
services:
  app:
    image: php:8.2-apache
    container_name: ${COOLIFY_APP_NAME}_php
    volumes:
      - ${COOLIFY_VOLUME_APP}:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_NAME=${COOLIFY_DATABASE_NAME}
      - DB_USER=${COOLIFY_DATABASE_USER}
      - DB_PASSWORD=${COOLIFY_DATABASE_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network
    labels:
      - coolify.enable=true
  
  db:
    image: mysql:8.0
    container_name: ${COOLIFY_APP_NAME}_mysql
    environment:
      - MYSQL_DATABASE=${COOLIFY_DATABASE_NAME}
      - MYSQL_USER=${COOLIFY_DATABASE_USER}
      - MYSQL_PASSWORD=${COOLIFY_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${COOLIFY_DATABASE_ROOT_PASSWORD}
    volumes:
      - ${COOLIFY_VOLUME_DATABASE}:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: ${COOLIFY_APP_NAME}_redis
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COOLIFY_APP_NAME}_phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${COOLIFY_DATABASE_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network
    labels:
      - coolify.enable=true

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    name: ${COOLIFY_VOLUME_DATABASE}
    external: true
